### ISSUE TITLE
Consider using postman-to-openapi

### ISSUE THREAD

**Issue by mefellows** [pactflow/example-bi-directional-provider-postman#1]
See also https://github.com/joolfe/postman-to-openapi/issues/109

**Comment by YOU54F** [comment]
Tried this out in the above commit, however it doesn't generate a body schema

https://joolfe.github.io/postman-to-openapi/#responses-parsed-from-postman-collection-examples

> Note that this examples will be added in OpenAPI specification as a ‘Operation Object > Responses Objects > content > Media Type Object > example or examples’ and not as a schema.

```
          content:
            application/json:
              schema:
                type: object
              example:
                id: '09'
                name: Gem Visa
                type: CREDIT_CARD
                price: 99.99
                version: v1
```
